# Generated by Django 5.2.1 on 2025-05-31 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('image_count', models.IntegerField(default=0)),
                ('has_hours', models.BooleanField(default=False)),
                ('has_description', models.BooleanField(default=False)),
                ('has_menu', models.BooleanField(default=False)),
                ('business_hours', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='Restaurant', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('competitor_businesses', models.ManyToManyField(related_name='competitor_comparisons', to='comparator.businessprofile')),
                ('target_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_comparisons', to='comparator.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
