# Generated by Django 5.2.1 on 2025-05-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='business_hours',
        ),
        migrations.DeleteModel(
            name='Comparison',
        ),
    ]
