# Generated by Django 5.2.1 on 2025-06-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0002_remove_businessprofile_business_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Business Profile', 'verbose_name_plural': 'Business Profiles'},
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='accepts_credit_cards',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='accepts_reservations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Operating hours for each day'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='country',
            field=models.CharField(default='United States', max_length=50),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='cuisine_type',
            field=models.CharField(blank=True, help_text='Type of cuisine or service offered', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='established_year',
            field=models.IntegerField(blank=True, help_text='Year the business was established', null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='google_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Whether the business is currently operating'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='menu_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='offers_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='offers_dine_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='offers_takeout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='outdoor_seating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='popular_dishes',
            field=models.JSONField(blank=True, default=list, help_text='List of popular dishes or services'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='price_range',
            field=models.CharField(blank=True, choices=[('$', 'Budget-friendly'), ('$$', 'Moderate'), ('$$$', 'Upscale'), ('$$$$', 'High-end')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='special_features',
            field=models.JSONField(blank=True, default=list, help_text='List of special features or amenities'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='temporarily_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='yelp_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
