# Generated by Django 5.2.1 on 2025-06-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0003_alter_businessprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs from SerpAPI'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='reviews',
            field=models.JSONField(blank=True, default=list, help_text='List of reviews from SerpAPI'),
        ),
    ]
