# Generated by Django 5.2.1 on 2025-06-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0004_businessprofile_images_businessprofile_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='data_id',
            field=models.CharField(blank=True, help_text='SerpAPI data ID for fetching additional data', max_length=100, null=True),
        ),
    ]
